{{- if .Values.cron.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "stock-prices.fullname" . }}
  labels:
   {{- include "stock-prices.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.crontab }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.secret }}
                  key: password
            - name: DATABASE_URL
              value: postgres://{{ .Values.postgresql.user }}:$(DB_PASSWORD)@{{ .Values.postgresql.database }}/{{ .Values.postgresql.database }}?sslmode=require
            command: ["./bin/kcron.sh"]

          restartPolicy: OnFailure

{{- end }}
