# Generated by Django 4.2.5 on 2023-09-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
